apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ps-create-cron
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 4
      template:
        spec:
          containers:
            - name: app
              image: busybox
              command: [ "ps", "-a" ]
          restartPolicy: Never
