apiVersion: batch/v1
kind: Job
metadata:
  name: ps
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: app
          image: busybox
          command: [ "ps", "-a" ]
      restartPolicy: Never
