apiVersion: batch/v1
kind: Job
metadata:
  name: ps
spec:
  backoffLimit: 4
  template:
    spec:
      containers:
        - name: app
          image: busybox
          command: ["ps", "-a"]
      #     volumeMounts:
      #       - name: internal-test-claim
      #         mountPath: /mnt/test
      # volumes:
      #   - name: internal-test-claim
      #     persistentVolumeClaim:
      #       claimName: test-claim
      restartPolicy: Never