apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "32Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "125m"
