apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "400m"
            requests:
              memory: "32Mi"
              cpu: "50m"
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
            httpGet:
              path: /healthz
              port: 8080
              scheme: HTTP
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
            successThreshold: 1
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP

---

# https://kubernetes.io/docs/tasks/run-application/configure-pdb/
apiVersion: policy/v1beta1 # policy/v1 v1.21
kind: PodDisruptionBudget
metadata:
  name: application-pdb
spec:
  minAvailable: 2
  selector:
    matchLabels:
      name: application
