apiVersion: v1
kind: Service
metadata:
  name: application-service
spec:
  selector:
    name: application
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: application-service-public
spec:
  selector:
    name: application
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
