apiVersion: v1
kind: Pod
metadata:
  name: application
  labels:
    name: application
spec:
  containers:
    - name: application
      image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      resources:
        limits:
          memory: "128Mi"
          cpu: "250m"
        requests:
          memory: "32Mi"
          cpu: "125m"
