apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "125m"

  - apiVersion: v1
    kind: Service
    metadata:
      name: application-service
    spec:
      selector:
        name: application
      type: ClusterIP
      ports:
        - port: 80
          targetPort: 8080

  - apiVersion: v1
    kind: Service
    metadata:
      name: application-service-public
    spec:
      selector:
        name: application
      type: LoadBalancer
      ports:
        - port: 80
          targetPort: 8080
