apiVersion: v1
kind: LimitRange
metadata:
  name: limit-per-container
spec:
  limits:
    - max:
        cpu: "1000m"
        memory: "1Gi"
      min:
        cpu: "100m"
        memory: "100Mi"
      default:
        cpu: "500m"
        memory: "500Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-storage
spec:
  limits:
    - type: PersistentVolumeClaim
      max:
        storage: 5Gi
      min:
        storage: 500Mi