apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          env:
            - name: MY_ENV
              value: test1
            - name: MY_ENV_FROM_CONFIGMAP
              valueFrom:
                configMapKeyRef:
                  name: application-configmap
                  key: stage
          volumeMounts:
            - mountPath: /app
              name: configuration
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "32Mi"
              cpu: "250m"
            requests:
              memory: "32Mi"
              cpu: "125m"
      volumes:
        - name: configuration
          configMap:
            name: application-configmap
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: application-configmap
data:
  stage: test
  index.html: |
    <html>
    </html>

