apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    name: mysql
    stage: dev
  ports:
    - port: 3306
      targetPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: wordpress-service-public
spec:
  selector:
    name: wordpress
    release: wordpress
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80

---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: wordpress-ingress
# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             backend:
#               serviceName: wordpress-service
#               servicePort: 80