apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 3
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: nginx
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              readOnly: true
              name: my-internal-nginx
      volumes:
        - name: my-internal-nginx
          persistentVolumeClaim:
            claimName: my-nginx