apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-deployment
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: application
  template:
    metadata:
      name: application
      labels:
        name: application
    spec:
      containers:
        - name: application
          image: gcr.io/kubernetes-e2e-test-images/echoserver:2.2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "750m"
            requests:
              memory: "32Mi"
              cpu: "250m"
